exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README
  - pull.sh
  - deploy.sh
  - csv2yaml.py
  - json2yaml.py
  - drive.py
  - node_modules

kramdown:
  show_warnings: true

description: The Computer Science Undergraduate Association at UC Berkeley (CSUA)
